version: '3.8'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - internal
    restart: unless-stopped

  video-dubbing-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - MAX_FILE_SIZE=10485760
      - TTS_PROVIDER=web-speech-api
      - LOG_LEVEL=info
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - video-dubbing-api
    networks:
      - internal
    restart: unless-stopped

volumes:
  redis_data:

networks:
  internal:
    driver: bridge
